// examples/nuxt-app/app/app.vue
<script setup lang="ts">
/**
 * Server-rendered, and every control is a link.
 *
 * The rows arrive in the HTML already sorted, filtered and paged. With
 * `buildHref` the header sorts and the pagination pages by navigation, so the
 * table works before its JavaScript has loaded. Once it has, `navigate`
 * hands those same links to the router, so nothing reloads.
 */
import { computed } from "vue"
import {
  TrapeziumTable,
  applyStateToUrl,
  pickUrlState,
  stateFromUrl,
  type TableState,
  type UrlOptions,
} from "@trapezium/vue"

import { makePeople } from "./data"

useHead({ title: "Trapezium in Nuxt", htmlAttrs: { lang: "en" } })

const route = useRoute()
const router = useRouter()

const people = makePeople()

const columns = [
  { key: "name", pin: "start" },
  { key: "email" },
  { key: "team", filter: "set" },
  { key: "salary", type: "currency", filter: "range" },
  { key: "started", type: "date" },
  { key: "remote", type: "boolean" },
]

/*
  The table shows fifteen rows a page, so fifteen is its resting size: a URL
  with no size means fifteen, and a size of fifteen writes nothing. The same
  object goes to every read and every write so the two agree.
*/
const URL_OPTIONS: UrlOptions = { defaults: { pageSize: 15 } }

const state = computed(() =>
  stateFromUrl(route.query as Record<string, string | string[] | undefined>, URL_OPTIONS),
)

const href = (next: TableState) => applyStateToUrl("/", next, URL_OPTIONS)

/*
  Only the keys the URL carries are controlled from it; the selection and any
  dragged widths stay with the table. A change that would leave the URL where
  it is — a selection — is not a navigation.
*/
const controlled = computed(() => pickUrlState(state.value))
const onStateChange = (next: TableState) => {
  const url = href(next)
  if (url !== href(state.value)) void router.push(url)
}

</script>

<template>
  <main>
    <h1>Trapezium in Nuxt</h1>
    <p>
      Server-rendered, with every control a real link. Disable JavaScript and the header still
      sorts and the pagination still pages; sort a column and look at the address bar.
    </p>

    <TrapeziumTable
      :data="people"
      :columns="columns"
      :get-row-id="(person) => person.id"
      :state="controlled"
      :build-href="href"
      :search="{ placeholder: 'Search people' }"
      header-search
      :selection="{ isSelectable: (person) => person.team !== 'Sales' }"
      export
      :pagination="{ mode: 'pages', pageSize: 15, pageSizeOptions: [15, 30, 60] }"
      :format="{ currency: 'GBP', locale: 'en' }"
      aria-label="People"
      @update:state="onStateChange"
      @navigate="(href) => router.push(href)"
    />
  </main>
</template>

// examples/svelte-app/src/App.svelte
<script lang="ts">
  /**
   * The Svelte example.
   *
   * Two tables: one with nothing configured, and one with everything. The
   * actions column returns a DOM node — which is all a renderer has to be —
   * `bind:tableState` keeps the arrangement in a rune, and the switches change
   * the props live.
   */
  import { Table, type TableState } from "@trapezium/svelte"

  import Controls from "./Controls.svelte"
  import { makePeople, type Person } from "./data"

  const people = makePeople()

  let selected = $state<string[]>([])
  let tableState = $state<TableState | undefined>()

  let mode = $state("pages")
  let setFilters = $state(false)
  let selection = $state(true)
  let cards = $state(false)

  const columns = $derived([
    { key: "name", pin: "start" },
    { key: "email" },
    { key: "team", filter: setFilters ? "set" : true },
    { key: "salary", type: "currency", filter: setFilters ? "set" : "range" },
    { key: "started", type: "date" },
    { key: "remote", type: "boolean" },
    {
      key: "actions",
      header: "",
      sortable: false,
      filter: false,
      exportable: false,
      width: 110,
      render: ({ row }: { row: Person }) => {
        const button = document.createElement("button")
        button.className = "tpz-btn"
        button.textContent = "Say hello"
        button.addEventListener("click", () => window.alert(`${row.name} — ${row.email}`))
        return button
      },
    },
  ])

  const pagination = $derived(
    mode === "none" ? false : { mode, pageSize: 15, pageSizeOptions: [15, 30, 60] },
  )
</script>

<main>
  <h1>Trapezium in Svelte</h1>
  <p>The same table, the same markup, the same stylesheet — bound with runes.</p>

  <section>
    <h2>Nothing configured</h2>
    <Table data={people.slice(0, 6)} pagination={false} />
  </section>

  <section>
    <h2>Everything switched on</h2>
    <p>
      Drag a column header sideways to move it, or out of the table to remove it. Sales is looked
      after elsewhere, so those rows cannot be selected.
    </p>

    <Controls
      segments={[
        {
          label: "Pagination",
          value: mode,
          options: [
            { value: "pages", label: "Pages" },
            { value: "simple", label: "Prev / next" },
            { value: "loadMore", label: "Load more" },
            { value: "infinite", label: "Infinite" },
            { value: "none", label: "All rows" },
          ],
        },
      ]}
      switches={[
        { label: "Set filters", value: setFilters },
        { label: "Selection", value: selection },
        { label: "Card layout", value: cards },
      ]}
      onsegment={(label, value) => {
        if (label === "Pagination") mode = value
      }}
      onswitch={(label, value) => {
        if (label === "Set filters") setFilters = value
        if (label === "Selection") selection = value
        if (label === "Card layout") cards = value
      }}
    />

    <Table
      data={people}
      {columns}
      getRowId={(person) => person.id}
      search={{ placeholder: "Search people" }}
      headerSearch={true}
      selection={selection ? { isSelectable: (person) => person.team !== "Sales" } : false}
      responsive={cards ? "cards" : "scroll"}
      export={true}
      {pagination}
      format={{ currency: "GBP", locale: "en-GB" }}
      maxHeight={420}
      onSelectionChange={(ids) => (selected = ids)}
      bind:tableState
    />
    <p>{selected.length} selected · sorted by {tableState?.sort[0]?.key ?? "nothing"}</p>
  </section>
</main>
