// examples/playground/src/controls.tsx
import type { ReactNode } from "react"

/**
 * The switches above each example.
 *
 * Deliberately part of the example rather than the library: a table library has
 * no business shipping a settings panel. What it is for is trying the props
 * without editing code — flip pagination to infinite, turn a column's filter
 * into a set filter, and watch what changes.
 */

export type Choice<T extends string> = { value: T; label: string }

export function Controls({ children }: { children: ReactNode }) {
  return <div className="controls">{children}</div>
}

/** An on/off switch. */
export function Switch({
  label,
  checked,
  onChange,
}: {
  label: string
  checked: boolean
  onChange: (checked: boolean) => void
}) {
  return (
    <label className="switch">
      <input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />
      <span className="switch-track" aria-hidden="true" />
      <span>{label}</span>
    </label>
  )
}

/** A row of mutually exclusive choices, which reads better than a select for three or four. */
export function Segmented<T extends string>({
  label,
  value,
  options,
  onChange,
}: {
  label: string
  value: T
  options: Choice<T>[]
  onChange: (value: T) => void
}) {
  return (
    <div className="segmented">
      <span className="segmented-label">{label}</span>
      <div className="segmented-options" role="group" aria-label={label}>
        {options.map((option) => (
          <button
            key={option.value}
            type="button"
            data-active={option.value === value}
            aria-pressed={option.value === value}
            onClick={() => onChange(option.value)}
          >
            {option.label}
          </button>
        ))}
      </div>
    </div>
  )
}

// examples/svelte-app/src/Controls.svelte
<script lang="ts">
  /**
   * The switches above the table.
   *
   * Part of the example rather than the library: a table library has no
   * business shipping a settings panel. What it is for is trying the props
   * without editing code.
   */
  type Segment = { label: string; value: string; options: { value: string; label: string }[] }
  type Toggle = { label: string; value: boolean }

  let {
    segments = [],
    switches = [],
    onsegment,
    onswitch,
  }: {
    segments?: Segment[]
    switches?: Toggle[]
    onsegment?: (label: string, value: string) => void
    onswitch?: (label: string, value: boolean) => void
  } = $props()
</script>

<div class="controls">
  {#each segments as segment (segment.label)}
    <div class="segmented">
      <span class="segmented-label">{segment.label}</span>
      <div class="segmented-options" role="group" aria-label={segment.label}>
        {#each segment.options as option (option.value)}
          <button
            type="button"
            data-active={option.value === segment.value}
            aria-pressed={option.value === segment.value}
            onclick={() => onsegment?.(segment.label, option.value)}
          >
            {option.label}
          </button>
        {/each}
      </div>
    </div>
  {/each}

  {#each switches as toggle (toggle.label)}
    <label class="switch">
      <input
        type="checkbox"
        checked={toggle.value}
        onchange={(event) => onswitch?.(toggle.label, event.currentTarget.checked)}
      />
      <span class="switch-track" aria-hidden="true"></span>
      <span>{toggle.label}</span>
    </label>
  {/each}
</div>
